name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
    build-windows:
        runs-on: windows-2025 #windows-latest has issue with <gameinput.h>
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: 'recursive'
            - uses: ilammy/msvc-dev-cmd@v1
              with:
                arch: x64
            - name: CMake generate
              run: |
                cmake -S ${{github.workspace}} --preset x64-release
            - name: CMake build
              run: |
                cmake --build ${{github.workspace}}/out/build/x64-release --config Release
            - name: Put executable in root directory
              run: |
                cp ${{github.workspace}}/out/build/x64-release/src/Release/TopDownShooter.exe ${{github.workspace}}
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: topdown-windows-x64-release
                path: |
                    ${{github.workspace}}/TopDownShooter.exe
                    ${{github.workspace}}/assets/
                
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: 'recursive'
            - name: Install dependencies # from SDL3 docs.md
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential git make \
                pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
                libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
                libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
                libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
                libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev \
                libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev libfreetype6-dev
            - name: CMake generate
              run: |
                cmake -S ${{github.workspace}} --preset linux-release
            - name: CMake build
              run: |
                cmake --build ${{github.workspace}}/out/build/linux-release
            - name: Put executable in root directory
              run: |
                cp ${{github.workspace}}/out/build/linux-release/src/TopDownShooter ${{github.workspace}}
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: topdown-linux-x64-release	
                path: |
                    ${{github.workspace}}/TopDownShooter
                    ${{github.workspace}}/assets/

    build-mac-osx:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: 'recursive'
            - name: Install dependencies # Only need this for build
              run: |
                brew install freetype harfbuzz
            - name: CMake generate
              run: |
                cmake -S ${{github.workspace}} --preset macos-release
            - name: CMake build
              run: |
                cmake --build ${{github.workspace}}/out/build/macos-release --config Release
            - name: Put executable in root directory
              run: |
                cp ${{github.workspace}}/out/build/macos-release/src/Release/TopDownShooter ${{github.workspace}}
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: topdown-macos-arm64-release
                path: |
                    ${{github.workspace}}/TopDownShooter
                    ${{github.workspace}}/assets/