name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: 'recursive'
            - uses: ilammy/msvc-dev-cmd@v1
              with:
                arch: x64
            - name: CMake generate
              run: |
                cmake -S . -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
            - name: CMake build
              run: |
                cmake --build ${{github.workspace}}/build --config Release
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: topdown-windows-x64-Release
                path: ${{github.workspace}}/build/src/Release/
                
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: 'recursive'
            - name: CMake generate
              run: |
                cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DSDLMIXER_MIDI_FLUIDSYNTH=OFF
            - name: CMake build
              run: |
                cmake --build ${{github.workspace}}/build --config Release
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: topdown-linux-x64-Release
                path: ${{github.workspace}}/build/src/Release/