name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: 'recursive'
            - uses: ilammy/msvc-dev-cmd@v1
              with:
                arch: x64
            - name: CMake generate
              run: |
                cmake -S . -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
            - name: CMake build
              run: |
                cmake --build ${{github.workspace}}/build --config Release
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: topdown-windows-x64-Release
                path: ${{github.workspace}}/build/src/Release/
                
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: 'recursive'
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential git make \
                pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
                libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
                libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
                libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
                libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev \
                libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev
            - name: CMake generate
              run: |
                cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DSDLMIXER_MIDI_FLUIDSYNTH=OFF
            - name: CMake build
              run: |
                cmake --build ${{github.workspace}}/build --config Release
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: topdown-linux-x64-Release
                path: ${{github.workspace}}/build/src/Release/